Repository SOPT-TEAM9-Carrot/Carrot-iOS, pull requests merged in 2023-05, with the labels that each got.

#11 [Feat] #10 - Home Navigation View 구현
  CDS_CarrotJob/CDS_CarrotJob.xcodeproj/project.pbxproj
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/HomeNavigationView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/ViewController/HomeViewController.swift
  CDS_CarrotJob/CDS_CarrotJob/Utils/Extension/UITextField+.swift
Labels: 🐶 정, Feat

#16 [Feat] #12 - PartTimeJobCollectionViewCell 구현
  CDS_CarrotJob/CDS_CarrotJob.xcodeproj/project.pbxproj
  CDS_CarrotJob/CDS_CarrotJob/Data/Model/PartTimeJobModel.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/Cell/PartTimeJobCollectionViewCell.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/ViewController/PartTimeJobCellTestViewController.swift
  CDS_CarrotJob/CDS_CarrotJob/Utils/CustomClass/AdvertisingButton.swift
  CDS_CarrotJob/CDS_CarrotJob/Utils/CustomClass/PartTimeLabel.swift
Labels: 🐶 정, Feat

#21 [Feat] #17 - ReviewTableViewCell 구현
  CDS_CarrotJob/CDS_CarrotJob.xcodeproj/project.pbxproj
  CDS_CarrotJob/CDS_CarrotJob/Data/Model/PartTimeJobModel.swift
  CDS_CarrotJob/CDS_CarrotJob/Data/Model/ReviewModel.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/ViewController/PartTimeJobCellTestViewController.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Review/Cell/ReviewTableViewCell.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Review/ViewController/ReviewViewController.swift
Labels: 🐶 정, Feat

#26 Feature/#20 HomeCollectionView 코드리뷰 반영
  CDS_CarrotJob/CDS_CarrotJob.xcodeproj/project.pbxproj
  CDS_CarrotJob/CDS_CarrotJob/Application/SceneDelegate.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/HomeLocalJobCollectionViewCell.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/HomeLocalJobView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/jobModel.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/ViewController/HomeLoaclJobViewController.swift
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/good.imageset/Contents.json
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/good.imageset/image 1 (3) 1.png
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/good.imageset/image 1 (3) 2.png
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/good.imageset/image 1 (3).png
Labels: 🐻‍❄️ 동현, Fix

#23 [Feat] #18 - MainDetailView 와 DetailProfileView 를 구현했습니다.
  CDS_CarrotJob/.swiftlint.yml
  CDS_CarrotJob/CDS_CarrotJob.xcodeproj/project.pbxproj
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailLocalList/DetailLocalListView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailProfile/Components/EmployerProfileStackView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailProfile/Components/KaKaoMapView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailProfile/DetailProfileView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/JobDetail.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/MainDetail/Components/JobInformationStackView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/MainDetail/Components/JobLocalInformingView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/MainDetail/Components/JobStatisticsView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/MainDetail/Components/JobTitleStackView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/MainDetail/Components/LabelWithImage.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/MainDetail/MainDetailView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/ViewController/JobDetailViewController.swift
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/KakaoMarker.imageset/Contents.json
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/KakaoMarker.imageset/KakaoMarker.png
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/carrotCalendarFill.imageset/carrotCalendarFill.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/carrotFace.imageset/Contents.json
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/carrotFace.imageset/carrotFace.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/carrotTalkBubble.imageset/carrotTalkBubble.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/employerProfile.imageset/Contents.json
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/employerProfile.imageset/employerProfile.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/kakaoMapDummyImage.imageset/Contents.json
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/kakaoMapDummyImage.imageset/kakaoMapDummyImage.png
  CDS_CarrotJob/CDS_CarrotJob/Utils/Extension/Int+.swift
  CDS_CarrotJob/CDS_CarrotJob/Utils/Extension/UIImage+.swift
  CDS_CarrotJob/CDS_CarrotJob/Utils/NameSpace/Color.swift
Labels: 🦊 규보, Feat, Fix, Rename

#28 [Feat] #22 - ReviewViewController 구현
  CDS_CarrotJob/CDS_CarrotJob/Application/AppDelegate.swift
  CDS_CarrotJob/CDS_CarrotJob/Application/SceneDelegate.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/HomeLocalJobCollectionViewCell.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/HomeLocalJobView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/ViewController/HomeLoaclJobViewController.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Review/ViewController/ReviewViewController.swift
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/carrotBack.imageset/Contents.json
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/carrotBack.imageset/Group 10.png
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/carrotBack.imageset/Group 10@2x.png
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/carrotBack.imageset/Group 10@3x.png
  CDS_CarrotJob/CDS_CarrotJob/Utils/NameSpace/Image.swift
Labels: 🐶 정, Feat

#30 [Fix] #24 - setUnderLineHidden 함수 추가
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/Cell/PartTimeJobCollectionViewCell.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/HomeLocalJobCollectionViewCell.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailLocalList/DetailLocalListView.swift
Labels: 🐶 정, Fix

#34 [Feat] #29 DetailReviewListView 를 구현합니다.
  CDS_CarrotJob/CDS_CarrotJob.xcodeproj/project.pbxproj
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailLocalList/DetailLocalListView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailProfile/DetailProfileView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailReviewList/Components/ApplicantsCommentsBox.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailReviewList/Components/DetailReviewPagingView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailReviewList/Components/DetailReviewSegmentView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailReviewList/DetailReviewEmptyView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailReviewList/DetailReviewListView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/MainDetail/MainDetailView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/ViewController/JobDetailViewController.swift
Labels: 🦊 규보, Feat

#36 [Feat] #33, #35 - View 에 애니메이션을 추가하고 API 를 모두 연결했습니다.
  CDS_CarrotJob/CDS_CarrotJob.xcodeproj/project.pbxproj
  CDS_CarrotJob/CDS_CarrotJob/Data/Model/JobDetailNetworkManager.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/Cell/PartTimeJobCollectionViewCell.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/BottomStickyView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailLocalList/DetailLocalListView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailProfile/Components/EmployerProfileStackView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailProfile/Components/KaKaoMapView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailProfile/DetailProfileView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailReviewList/Components/DetailReviewPagingView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailReviewList/Components/DetailReviewSegmentView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailReviewList/DetailReviewListView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/JobDetailNavigationBarView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/JobDetailToastView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/MainDetail/Cell/CategoryCollectionViewCell.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/MainDetail/Components/JobInformationStackView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/MainDetail/Components/JobTitleStackView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/MainDetail/MainDetailView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/ViewController/JobDetailViewController.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Review/Cell/ReviewTableViewCell.swift
  CDS_CarrotJob/CDS_CarrotJob/Resource/Info.plist
Labels: 🦊 규보, Feat, Fix

#37 [Feat] #32 - HomeViewConotroller 구현
  CDS_CarrotJob/CDS_CarrotJob.xcodeproj/project.pbxproj
  CDS_CarrotJob/CDS_CarrotJob/Application/SceneDelegate.swift
  CDS_CarrotJob/CDS_CarrotJob/Data/Model/Home/JobLabelModel.swift
  CDS_CarrotJob/CDS_CarrotJob/Data/Model/PartTimeJobModel.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/Cell/PartTimeJobCollectionViewCell.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/HomeLocalJobView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/HomeScrollView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/Near/Cell/JobLabelCollectionViewCell.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/Near/Cell/TodayPopularCollectionViewCell.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/Near/View/HomeNearJobView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/Near/View/JobLabelFooterView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/Near/View/TodayPopularFooterView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/Near/View/TodayPopularHeaderView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/ViewController/HomeViewController.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/ViewController/PartTimeJobCellTestViewController.swift
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/applyImage.imageset/Contents.json
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/applyImage.imageset/image 24.png
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/applyImage.imageset/image 24@2x.png
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/applyImage.imageset/image 24@3x.png
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/blackArrow.imageset/Contents.json
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/blackArrow.imageset/Vector.png
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/blackArrow.imageset/Vector@2x.png
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/blackArrow.imageset/Vector@3x.png
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/whiteArrow.imageset/Contents.json
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/whiteArrow.imageset/Vector.png
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/whiteArrow.imageset/Vector@2x.png
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/whiteArrow.imageset/Vector@3x.png
  CDS_CarrotJob/CDS_CarrotJob/Utils/Extension/UICollectionView+.swift
  CDS_CarrotJob/CDS_CarrotJob/Utils/Extension/UILabel+.swift
  CDS_CarrotJob/CDS_CarrotJob/Utils/NameSpace/Image.swift
Labels: 🐶 정, Feat

#42 [Feat] #41 - PartTimeJob 서버통신 완료
  CDS_CarrotJob/CDS_CarrotJob.xcodeproj/project.pbxproj
  CDS_CarrotJob/CDS_CarrotJob/Data/DTO/Home/HomePartTimeResponse.swift
  CDS_CarrotJob/CDS_CarrotJob/Data/DTO/Review/ReviewResponse.swift
  CDS_CarrotJob/CDS_CarrotJob/Network/APIService/Home/HomePartTimeJobService.swift
  CDS_CarrotJob/CDS_CarrotJob/Network/APIService/Review/ReviewService.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/Near/View/HomeNearJobView.swift
Labels: 🐶 정, Feat

#43 [Feat] #27 -ProfileView 구현 + HomeLocalView Server 연결
  CDS_CarrotJob/CDS_CarrotJob.xcodeproj/project.pbxproj
  CDS_CarrotJob/CDS_CarrotJob/Application/AppDelegate.swift
  CDS_CarrotJob/CDS_CarrotJob/Application/SceneDelegate.swift
  CDS_CarrotJob/CDS_CarrotJob/Data/DTO/Home/HomeRecommandResponse.swift
  CDS_CarrotJob/CDS_CarrotJob/Network/APIService/Home/HomeRecommendService.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Apply/View/Apply.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Apply/ViewController/ApplyViewController.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/HomeLocalJobCollectionViewCell.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/HomeLocalJobView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/jobModel.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailLocalList/DetailLocalListView.swift
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/Image.imageset/Component 40.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/Image.imageset/Component 41.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/Image.imageset/Component 42.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/Image.imageset/Contents.json
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/border.imageset/Contents.json
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/border.imageset/Rectangle 106.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/border.imageset/Rectangle 107.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/border.imageset/Rectangle 108.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/man.imageset/Contents.json
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/man.imageset/man 1.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/man.imageset/man 2.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/man.imageset/man.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/register.imageset/Component 42.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/register.imageset/Component 43.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/register.imageset/Component 44.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/register.imageset/Contents.json
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/woman.imageset/Contents.json
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/woman.imageset/woman 1.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/woman.imageset/woman 2.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/woman.imageset/woman.svg
Labels: 🐻‍❄️ 동현, Feat

#48 [Feat] #46 - 모든 뷰를 잇습니다.
  CDS_CarrotJob/CDS_CarrotJob/Network/APIService/Review/ReviewService.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Apply/View/Apply.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/HomeLocalJobView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/HomeScrollView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/ViewController/HomeViewController.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/BottomStickyView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailReviewList/Components/DetailReviewPagingView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailReviewList/DetailReviewListView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/JobDetailNavigationBarView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/ViewController/JobDetailViewController.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Review/Cell/ReviewTableViewCell.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Review/ViewController/ReviewViewController.swift
Labels: 🦊 규보, 🐻‍❄️ 동현, 🐶 정, Feat, Fix, Merge

#49 [Fix] #44 - 자잘한 레이아웃 수정
  CDS_CarrotJob/CDS_CarrotJob/Data/Model/PartTimeJobModel.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/Cell/PartTimeJobCollectionViewCell.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/HomeNavigationView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/HomeScrollView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/Near/View/HomeNearJobView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/ViewController/HomeViewController.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/ViewController/PartTimeJobCellTestViewController.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Review/ViewController/ReviewViewController.swift
Labels: 🐶 정, Fix

#50 Feature/#45
  CDS_CarrotJob/CDS_CarrotJob.xcodeproj/project.pbxproj
  CDS_CarrotJob/CDS_CarrotJob/Application/SceneDelegate.swift
  CDS_CarrotJob/CDS_CarrotJob/Data/DTO/Profile/ProfileRegisterResponse.swift
  CDS_CarrotJob/CDS_CarrotJob/Network/APIService/Profile/ProfileService.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Apply/View/Apply.swift
  CDS_CarrotJob/CDS_CarrotJob/Profile/ProfileRegister.swift
Labels: 🐻‍❄️ 동현, Feat

#52 우리는 해냈다.
  CDS_CarrotJob/CDS_CarrotJob.xcodeproj/project.pbxproj
  CDS_CarrotJob/CDS_CarrotJob/Application/SceneDelegate.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Apply/View/Apply.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Apply/View/ApplyNavigation.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Apply/ViewController/ApplyViewController.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/HomeLocalJobCollectionViewCell.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/JobDetail/View/DetailReviewList/Components/DetailReviewPagingView.swift
Labels: 🦊 규보, 🐻‍❄️ 동현, 🐶 정, Feat

#53 [Setting] #51 - 폴더링
  CDS_CarrotJob/CDS_CarrotJob.xcodeproj/project.pbxproj
  CDS_CarrotJob/CDS_CarrotJob/Data/Model/Home/JobModel.swift
  CDS_CarrotJob/CDS_CarrotJob/Data/Model/Home/PartTimeJobModel.swift
  CDS_CarrotJob/CDS_CarrotJob/Data/Model/JobDetail/JobDetailNetworkManager.swift
  CDS_CarrotJob/CDS_CarrotJob/Data/Model/Review/ReviewModel.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Apply/View/ApplyNavigation.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Apply/View/ApplyView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Apply/ViewController/ApplyViewController.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/Home/HomeNavigationView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/Home/HomeScrollView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/LocalJob/Cell/HomeLocalJobCollectionViewCell.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/LocalJob/View/HomeLocalJobView.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/Near/Cell/PartTimeJobCollectionViewCell.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/home.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/View/jobModel.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/ViewController/HomeLoaclJobViewController.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Home/ViewController/PartTimeJobCellTestViewController.swift
  CDS_CarrotJob/CDS_CarrotJob/Presentation/Review/View/Review.swift
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/camera.imageset/Component 40.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/camera.imageset/Component 41.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/camera.imageset/Component 42.svg
  CDS_CarrotJob/CDS_CarrotJob/Resource/AssetCatalog/Image.xcassets/camera.imageset/Contents.json
Labels: 🦊 규보, 🐻‍❄️ 동현, 🐶 정, Rename, Setting
